/* QUESTION 3*/

/*Course table is previously created*/
/*It has auto-generated primary key*/
SELECT * FROM COURSE;

/* There is a many:1 relation between subject and course*/
CREATE TABLE SUBJECT(
    ID NUMBER PRIMARY KEY,
    SUBJECT VARCHAR2(20) NOT NULL,
    COURSE_ID NUMBER REFERENCES COURSE(ID));
    
INSERT INTO SUBJECT VALUES(1001, 'Calculus', 1);
INSERT INTO SUBJECT VALUES(1002, 'Trigonometry', 1);
INSERT INTO SUBJECT VALUES(1003, 'Geometry', 1);

INSERT INTO SUBJECT VALUES(2001, 'Quantum Mechanics', 2);
INSERT INTO SUBJECT VALUES(2002, 'Thermodynamics', 2);

INSERT INTO SUBJECT VALUES(2201, 'Zoology', 22);
INSERT INTO SUBJECT VALUES(2202, 'Botany', 22);


SELECT * FROM SUBJECT;

/* There is a 1:many relation between subject and professor*/    
CREATE TABLE PROFESSOR(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    SUB_ID NUMBER REFERENCES SUBJECT(ID));
    
INSERT INTO PROFESSOR VALUES(10, 'Salil', 1001);
INSERT INTO PROFESSOR VALUES(11, 'Samrat', 1001);
INSERT INTO PROFESSOR VALUES(12, 'Subhashree', 1002);

INSERT INTO PROFESSOR VALUES(13, 'Surajit', 2001);
INSERT INTO PROFESSOR VALUES(14, 'Sonu', 2001);  

INSERT INTO PROFESSOR VALUES(15, 'Anindya', 2202);
INSERT INTO PROFESSOR VALUES(16, 'Shreya', 2202);


SELECT * FROM PROFESSOR;






    
    